services:
  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"

  backend:
    build: ./server
    container_name: node_backend
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  worker:
    build: ./server
    container_name: node_worker
    command: nodemon --legacy-watch worker.js   # run worker instead of index.js
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
